---
layout: default
title: 有关Promise
theme: JavaScript
---

<p>去年六月份，ES2015正式发布（也就是ES6），其中Promise被列为正式规范。作为ES6中最重要的特性之一，我们有必要掌握并理解透彻。</p>

<p>复杂的概念先不讲，我们先简单粗暴地把Promise用一下，有个直观感受。那么第一个问题来了，Promise是什么玩意呢？是一个类？对象？数组？函数？</p>

<p>别猜了，直接打印出来看看吧，<code>console.dir(Promise)</code></p>

<p><img src="http://mmbiz.qpic.cn/mmbiz/zPh0erYjkib0In4GI5qAQJR4yOnveEa5VrXNmILo6dmTwX8D8mZRj9RMib0WLv7SmbDPWpPr78qx0edv0qxUiaHaw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1" alt="promise" /></p>

<p>这么一看就明白了，Promise是一个构造函数，自己身上有all, reject, resolve这几个眼熟的方法，源性上有then, catch等同样很眼熟的方法。这么说用Promise new出来的对象肯定就有then, catch等方法了。</p>

<p>那就new一个玩玩吧。</p>

<p>
  <pre>
    var p = new Promise(function (resolve, reject) {
      setTimeout(function () {
        console.log('执行完成');
        resolve('随便什么数据');
      }, 2000);
    });
  </pre>
</p>

<p>Promise的构造函数接收一个参数，是函数，并且传入两个参数：resolve, reject。分别表示异步操作执行成功后的回调函数和异步操作执行失败后的回调函数。</p>

<p>其实这里用成功和失败来描述并不准确，按照标准来讲，resolve是将Promise的状态置为fullfiled，reject是将Promise的状态置为rejcted。不过在我们开始阶段可以先这么理解，后面再细究概念。</p>

<p>在上面的代码中，我们执行了一个异步操作，也就是setTimeout，2秒后，输出"执行完成"，并且调用resolve方法。</p>

<p>运行代码，会在2秒后输出"执行完成"。注意！我只是new了一个对象，并没有调用它，我们传进去的函数就已经执行了，这是需要注意的一个细节。所以我们用Promise的时候一般是包在一个函数中，在需要的时候运行这个函数，如：</p>

<p>
  <pre>
    function runAsync() {
      var p = new Promise(function (resolve, reject) {
        setTimeout(function () {
          console.log('执行完成');
          resolve('随便什么数据');
        });
      });
    }
    runAsync();
  </pre>
</p>

<p>这时候你应该有两个疑问：1.包装这么一个函数有毛线用？2.resolve('随便什么数据');这是干毛的？</p>

<p>我们继续来说。在我们包装好的函数最后，会return出Promise对象，也就是说，执行这个函数我们得到了一个Promise对象。还记得Promise对象上有then, catch方法吧？这就是强大之处了，看下面的代码：</p>

<p>
  <pre>
    runAsync().then(function (data) {
      console.log(data);
    });
  </pre>
</p>

<p>在runAsync()的返回上直接调用then方法，then接收一个参数，是函数，并且会拿到我们在runAsync中调用resolve时传的参数。运行这段代码，会在2秒后输出"执行完成"，紧接着输出"随便什么数据"。</p>

<p>这时候你应该有所领悟了，原来then里面的函数就跟我们平时的回调函数一个意思，能够在runAsync这个异步任务执行完成之后被执行。这就是Promise的作用了，简单来讲，就是能把原来的回调写法分离出来，在异步操作执行完成后，用链式调用的方式执行回调函数。</p>

<p>你可能会不屑一顾，那么牛逼轰轰的Promise就这点能耐？我把回调函数封装一下，给runAsync传进去不也一样吗，就像这样：</p>

<p>
  <pre>
    function runAsync(callback) {
      setTimeout(function () {
        console.log('执行完成');
        callback('随便什么数据');
      });
    }
    runAsync(function (data) {
      console.log(data);
    });
  </pre>
</p>

<p>效果也是一样的，还费劲用Promise干嘛。那么问题来了，有多层回调该怎么办？如果callback也是一个异步操作，而且执行完后也需要有相应的回调函数，该怎么办呢？</p>

<p>总不能再定义一个callback2，然后给callback传进去吧。而Promise得优势在于，可以在then方法中继续写Promise对象并返回，然后继续调用then来进行回调操作。</p>

<p>链式操作的用法</p>

<p>所以，从表面上看，Promise只是能够简化层层回调的写法，而实质上，Promise的精髓是"状态"，用维护状态、传递状态的方式来使得回调函数能够及时调用，它比传递callback函数要简单、灵活的多。所以使用Promise的正确场景是这样的。</p>

<p>
  <pre>
    runAsync1()
    .then(function (data) {
      console.log(data);
      return runAsync2();
    })
    .then(function (data) {
      console.log(data);
      return runAsync3();
    })
    .then(function (data) {
      console.log(data);
    });
  </pre>
</p>

<p>这样能够按照顺序，每隔两秒输出每个异步回调中的内容，在runAsync2中传给resolve的数据，能在接下来的then方法中拿到。运行结果如下：</p>

<p><img src="http://mmbiz.qpic.cn/mmbiz/zPh0erYjkib0In4GI5qAQJR4yOnveEa5VdPSlVp9doBBOhzN7TIeHW0j6UIDZFQzzW5MoHibOOzY0eozOty2SGeQ/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1" alt="result" /></p>

<p>runAsync1, runAsync2, runAsync3这三个函数都是如何定义的？</p>

<p>
  <pre>
    function runAsync1() {
      var p = new Promise(function (resolve, reject) {
        setTimeout(function () {
          console.log('异步任务1执行完成');
          resolve('随便什么数据1');
        }, 1000);
      });
      return p;
    }
    function runAsync2() {
      var p = new Promise(function (resolve, reject) {
        setTimeout(function () {
          console.log('异步任务2执行完成');
          resolve('随便什么数据2');
        }, 1000);
      });
      return p;
    }
    function runAsync3() {
      var p = new Promise(function (resolve, reject) {
        setTimeout(function () {
          console.log('异步任务3执行完成');
          resolve('随便什么数据3');
        }, 1000);
      });
      return p;
    }
  </pre>
</p>

<p>在then方法中，你也可以直接return 数据而不是Promise对象，在后年的then中就可以接收到数据了，比如我们把上面的代码修改成这样。</p>

<p>
  <pre>
    runAsync1()
    .then(function (data) {
      console.log(data);
      return runAsync2();
    })
    .then(function (data) {
      console.log(data);
      return '直接返回数据';  // 这里直接返回数据
    })
    .then(function (data) {
      console.log(data);
    });
  </pre>
</p>

<p>那么输出就变成了这样：</p>

<p><img src="http://mmbiz.qpic.cn/mmbiz/zPh0erYjkib0In4GI5qAQJR4yOnveEa5Vr3mPllvIbRDjicsFiaOPhoCFnpJPOtWgVLoG6yaDCzQ1icm2JxhzZ2giaQ/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1" alt="result2" /></p>

<p>reject的用法</p>

<p>到这里，你应该对"promise是什么玩意"有了最基本的了解。那么我们接着来看看ES6的Promise还有什么功能。我们光用了resolve，还没用reject呢，它是做什么的呢？</p>

<p>事实上，我们前面的例子都是只有"执行成功"的回调，还没有失败的情况，reject的作用就是把Promise的状态置为rejected，这样我们在then中就能捕捉到，然后执行"失败"情况的回调。</p>

<p>
  <pre>
    function getNumber() {
      var p = new Promise(function (resolve, reject) {
        setTimeout(function () {
          var num = Math.ceil(Math.random() * 10);
          if (num <= 5) {
            resolve(num);
          } else {
            reject('数字太大了');
          }
        }, 2000);
      });
      return p;
    }

    getNumber()
    .then(
      function (data) {
        console.log('resolved');
        console.log(data);
      },
      function (data) {
        console.log('rejected');
        console.log(reason);
      }
    );
  </pre>
</p>

<p>catch的用法</p>

<p>除了then方法之外，还有一个catch方法，它是做什么用的呢？其实它和then的第二个参数一样，用来指定reject回调，用法是这样：</p>

<p>
  <pre>
    getNumber()
    .then(function (data) {
      console.log('resolved');
      console.log(data);
    })
    .catch(function (reason) {
      console.log('rejected');
      console.log('reason');
    });
  </pre>
</p>

<p>效果和写在then的第二个参数里面一样。不过它还有另外一个作用：在执行resolve的回调（也就是上面then中的第一个参数）时，如果抛出异常了（代码出错了），那么并不会报错卡死js，而是会进到这个catch方法中。请看下面的代码：</p>

<p>
  <pre>
    getNumber()
    .then(function (data) {
      console.log('resolved');
      console.log(data);
      console.log(somedata);
    })
    .catch(function (reason) {
      console.log('rejected');
      console.log(reason);
    });
  </pre>
</p>

<p>在resolve的回调中，我们console.log(somedata);而somedata这个变量是没有被定义的。如果我们不用Promise，代码运行到这里就直接在控制台报错了，不往下运行了，但是在这里，会得到这样的结果：</p>

<p><img src="http://mmbiz.qpic.cn/mmbiz/zPh0erYjkib0In4GI5qAQJR4yOnveEa5VcIddhQkWoCJnUyH7D9CM9Er01u56ibdaC6ffFYEyEAkURwuoXglicJYA/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1" alt="result3" /></p>

<p>也就是说进到catch方法里面去了，而且把错误原因传到了reason参数中。即便是有错误的代码也不会报错了，这与我们的try/catch语句有相同的功能。</p>

<p>all的语法</p>

<p>Promise的all方法提供了并行执行异步操作的能力，并且在所有异步操作执行完后才执行回调。我们仍旧使用上面定义好的runAsync1, runAsync2, runAsync3这三个函数。看下面的例子：</p>

<p>
  <pre>
    Promise
    .all([runAsync1(), runAsync2(), runAsync3()])
    .then(function (results) {
      console.log(results);
    });
  </pre>
</p>

<p>用Promise.all来还行，all接收一个数组参数，里面的值最终都算返回Promise对象。这样，三个异步操作是并行执行的，等到它们都执行完后才会进到then里面。</p>

<p>那么，三个异步操作返回的数据哪里去了呢？都在then里面呢，all会把所有异步操作的结果放进一个数组传给then，就是上面的results，所以上面代码的输出结果就是：</p>

<p><img src="http://mmbiz.qpic.cn/mmbiz/zPh0erYjkib0In4GI5qAQJR4yOnveEa5V5EgFINwMuFfdUe0hHa3Lt7BOAibpkQG9IEpQm1l8nNIVypDqS14QDkA/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1" alt="result4" /></p>

<p>有了all，你就可以并行执行多个异步操作，并且在一个回调中处理所有的返回数据，是不是很酷？有一个场景是很适合这个的，一些游戏类的素材比较多的应用，打开网页时，与现价再需要用到各种资源如图片、flash以及各种静态文件。所有的都加载完后，我们再进行页面的初始化</p>

<p>race的用法</p>

<p>all方法的效果实际上是「谁跑得慢，以谁为准执行回调」，那么相对的就有另一个方法「谁跑的快，以谁为准执行回调」，这就是race方法，这个词本身就是赛跑的意思。race的用法和all一样，我们把上面runAsync1的延时改为1秒来看一下：</p>

<p>
  <pre>
    Promise.
    race([runAsync1(), runAsync2(), runAsync3()])
    .then(function (results) {
      console.log(results);
    });
  </pre>
</p>

<p>这三个异步操作同样是并行执行的。结果你应该可以猜到，1秒后runAsync1已经执行完了，此时then里面的就执行了。结果是这样的：</p>

<p><img src="http://mmbiz.qpic.cn/mmbiz/zPh0erYjkib0In4GI5qAQJR4yOnveEa5VXzqDQibET8fzeZsbvPhx0Tvk87ZV7jUJzMbNohRxa93hmfZnicbbvROw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1" alt="result5" /></p>

<p>总结</p>

<p>本文中所有异步操作均以setTimeout为例子，之所以不适用ajax是为了避免引起混淆，因为谈起ajax，很多人的第一反应就是jquery的ajax，而jquery又有自己的promsie实现。如果你理解了原理，就知道适用setTimeout和ajax是一个意思。</p>

<p>说起jquery，我不得不吐槽一句，jquery的promise实现太过垃圾，各种语法把人都搞蒙了，我认为promise之所以没有全面普及和jquery有很大的关系。</p>
